### ISSUE TITLE
Hi, what’s the latest update?

### ISSUE THREAD

**Issue by jddcef** [hagiostech/hebrew-greek-interlinear-bible#1]
Hi there,

Were you going to upload this amazing app?
Before something happens to you, God forbid,  and it’s all lost.

Thanks so far

**Comment by hagiostech** [comment]
Hi brother. I didn't think of that. I will give instructions to my wife if that happens. Thanks. May God continue blessing you.

**Comment by jddcef** [comment]
Good idea. I guess you do have a private a repo for working on it then, and your Will can just specify how to make it public.


All the best with the family, bro.
